#!/usr/bin/env node
// askSarah.ai v2 build. Zero dependencies.
//
//   node scripts/build.mjs            build published content
//   DRAFTS=1 node scripts/build.mjs   also render drafts (local preview only, never commit)
//
// Reads content/**, writes static HTML next to the existing hand-built pages,
// plus search-index.json and sitemap.xml. Existing pages are never touched
// except index.html (the homepage), which this script owns.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { header, footer, FONTS } from './chrome.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://asksarah.ai';
const SUBSCRIBE_URL = 'https://prsarahevans.substack.com/subscribe';
const DRAFTS = process.env.DRAFTS === '1';
const GENERATED = '<!-- Generated by scripts/build.mjs from content/. Edit the content files, not this page. -->';

// ---------- load ----------
const readJSON = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));
function loadDir(dir) {
  const full = path.join(ROOT, 'content', dir);
  if (!fs.existsSync(full)) return [];
  return fs.readdirSync(full)
    .filter((f) => f.endsWith('.json') && !f.startsWith('_'))
    .map((f) => ({ ...readJSON(path.join(full, f)), _file: `content/${dir}/${f}` }))
    .filter((x) => x.published !== false || DRAFTS);
}
const C = {
  skill: loadDir('skills'),
  pack: loadDir('packs'),
  stack: loadDir('stack'),
  'ai-use': loadDir('ai-uses'),
  shortcut: loadDir('shortcuts'),
  system: loadDir('systems'),
  edit: loadDir('edit'),
};
const articles = readJSON(path.join(ROOT, 'content', 'articles.json'));

// ---------- validation ----------
const errors = [];
const checkoutSrc = fs.readFileSync(path.join(ROOT, 'api', 'create-checkout.js'), 'utf8');
const stripePrices = {};
for (const m of checkoutSrc.matchAll(/'([a-z0-9-]+)':\s*\{\s*name:\s*'[^']*',\s*priceInCents:\s*(\d+)/g)) stripePrices[m[1]] = Number(m[2]);
for (const s of C.skill) {
  if (!s.slug || !s.title) errors.push(`${s._file}: needs slug and title`);
  if (s.free_or_paid === 'paid' && s.status === 'available') {
    const id = s.stripe_id || s.slug;
    if (!(id in stripePrices)) errors.push(`${s._file}: stripe_id "${id}" isn't in api/create-checkout.js, so checkout would fail`);
    else if (Math.round(Number(s.price) * 100) !== stripePrices[id])
      errors.push(`${s._file}: price ${s.price} doesn't match api/create-checkout.js (${stripePrices[id] / 100}). Change both or neither.`);
  }
}
if (errors.length) { console.error('Build stopped:\n  ' + errors.join('\n  ')); process.exit(1); }

// ---------- helpers ----------
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const arr = (v) => (Array.isArray(v) ? v : v ? [v] : []);
const has = (v) => (Array.isArray(v) ? v.length > 0 : v !== null && v !== undefined && String(v).trim() !== '');
const fmtPrice = (p) => (Number(p) % 1 === 0 ? `$${Number(p)}` : `$${Number(p).toFixed(2)}`);
const fmtDate = (d) => (d ? new Date(d + 'T12:00:00Z').toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' }) : '');
const paras = (v) => arr(v).map((p) => `<p>${esc(p)}</p>`).join('\n');
const list = (v, cls = 'ticks') => (has(v) ? `<ul class="${cls}">${arr(v).map((x) => `<li>${esc(x)}</li>`).join('')}</ul>` : '');

const TYPES = {
  skill: { label: 'Skill', base: '/skills' },
  pack: { label: 'Skill Pack', base: '/skills' },
  stack: { label: "Sarah's Stack", base: '/stack' },
  'ai-use': { label: 'How I use AI', base: '/things-ai-can-do' },
  shortcut: { label: 'Shortcut', base: '/shortcuts' },
  system: { label: 'System', base: '/systems' },
  edit: { label: "Sarah's Edit", base: '/edit' },
  article: { label: 'Article', base: '' },
};
function urlFor(type, item) {
  if (type === 'pack') return `/skills#${item.slug}`; // pack pages arrive in Phase 2
  if (type === 'article') return `/${item.slug}`;
  return `${TYPES[type].base}/${item.slug}`;
}
function find(type, slug) {
  if (type === 'article') return articles.find((a) => a.slug === slug);
  return (C[type] || []).find((x) => x.slug === slug);
}
function badgeFor(type, item) {
  if (type === 'skill' || type === 'pack') {
    if (item.status === 'coming-soon') return item.free_or_paid === 'paid'
      ? { text: item.price ? `${fmtPrice(item.price)} · Coming soon` : 'Coming soon', cls: 'badge-soon' }
      : { text: 'Free · Coming soon', cls: 'badge-free' };
    return item.free_or_paid === 'paid' ? { text: fmtPrice(item.price), cls: 'badge-paid' } : { text: 'Free', cls: 'badge-free' };
  }
  if (type === 'ai-use') return { text: `#${item.number}`, cls: 'badge-new' };
  return null;
}
const summaryOf = (type, it) => it.description || it.promise || it.short_description || it.what_i_use_it_for || it.problem || it.why_i_like_it || '';
const titleOf = (it) => it.title || it.name;

function card(type, item, { showType = false, trackId = '' } = {}) {
  const b = badgeFor(type, item);
  const url = urlFor(type, item);
  return `<article class="card"${item.category ? ` data-cats="${esc(arr(item.category).join('|'))}"` : ''}>
  <div class="badges">${showType ? `<span class="badge badge-type">${esc(TYPES[type].label)}</span>` : ''}${b ? `<span class="badge ${b.cls}">${esc(b.text)}</span>` : ''}${item.new && item.status !== 'coming-soon' ? '<span class="badge badge-new">New</span>' : ''}</div>
  <h3><a href="${url}"${trackId ? ` data-track="related_click" data-track-id="${esc(trackId)}"` : ''}>${esc(titleOf(item))}</a></h3>
  <p>${esc(summaryOf(type, item))}</p>
  <div class="card-foot"><span>${esc(arr(item.category).join(' · '))}</span><span class="go" aria-hidden="true">→</span></div>
</article>`;
}

function related(item, fromId) {
  const items = arr(item.related_items)
    .map((r) => ({ type: r.type, it: find(r.type, r.slug) }))
    .filter((r) => r.it && (r.it.published !== false || DRAFTS))
    .slice(0, 4);
  if (!items.length) return '';
  return `<aside class="related" aria-labelledby="rel-h"><h2 id="rel-h">Where to go next</h2><div class="grid">${items
    .map((r) => card(r.type, r.it, { showType: true, trackId: `${fromId}->${r.type}:${r.it.slug}` }))
    .join('')}</div></aside>`;
}

const searchForm = (id = 'q-home') => `<form class="search-form" action="/search" method="get" role="search">
  <label class="sr-only" for="${id}">What are you trying to figure out?</label>
  <input id="${id}" name="q" type="search" placeholder="Try &quot;meetings&quot;" autocomplete="off">
  <button class="btn btn-primary" type="submit">Ask</button>
</form>`;

const capture = (heading = "I'll send you the useful stuff. Not every thought I've ever had.", sub = 'New Skills, shortcuts and things worth using.') => `<div class="capture">
  <div><h2>${esc(heading)}</h2><p>${esc(sub)}</p></div>
  <a class="btn btn-primary" href="${SUBSCRIBE_URL}" target="_blank" rel="noopener" data-track="email_signup_click">Get the emails →</a>
</div>`;

// ---------- layout ----------
function layout({ title, description, pathname, body, jsonld = [], ogType = 'website', view = '', viewId = '', draft = false, banner = '' }) {
  const canonical = SITE + (pathname === '/' ? '' : pathname);
  const ld = jsonld.filter(Boolean).map((j) => `<script type="application/ld+json">${JSON.stringify(j)}</script>`).join('\n  ');
  return `<!DOCTYPE html>
${GENERATED}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">
  <link rel="canonical" href="${canonical}">
  <meta property="og:type" content="${ogType}">
  <meta property="og:site_name" content="askSarah.ai">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(description)}">
  <meta property="og:url" content="${canonical}">
  <meta property="og:image" content="${SITE}/og-image.png">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@prsarahevans">
  <meta name="twitter:title" content="${esc(title)}">
  <meta name="twitter:description" content="${esc(description)}">
  <meta name="twitter:image" content="${SITE}/og-image.png">
  ${draft ? '<meta name="robots" content="noindex">' : ''}
  <meta name="theme-color" content="#faf8f4" media="(prefers-color-scheme: light)">
  <meta name="theme-color" content="#121017" media="(prefers-color-scheme: dark)">
  <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 40'><text y='32' font-family='sans-serif' font-weight='700' font-size='28'><tspan fill='%23be185d'>ask</tspan><tspan fill='%2317151f'>S</tspan><tspan fill='%23ec4899'>.ai</tspan></text></svg>">
  <link rel="apple-touch-icon" href="/icon-192.png">
  <link rel="manifest" href="/manifest.json">
  ${FONTS}
  <link rel="stylesheet" href="/assets/chrome.css">
  <link rel="stylesheet" href="/assets/site.css">
  ${ld}
  <script defer src="/_vercel/insights/script.js"></script>
</head>
<body${view ? ` data-view="${esc(view)}" data-view-id="${esc(viewId)}"` : ''}>
${draft ? '<div class="draft-banner">DRAFT PREVIEW. Not published. Built with DRAFTS=1.</div>' : ''}
${banner}
${header(pathname)}
<main id="main">
${body}
</main>
${footer()}
<script src="/assets/site.js" defer></script>
</body>
</html>
`;
}

// ---------- writers ----------
const written = [];
function write(pathname, html) {
  const file = pathname === '/' ? 'index.html' : pathname.replace(/^\//, '') + '.html';
  const full = path.join(ROOT, file);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, html);
  written.push(pathname);
}

const personLD = { '@type': 'Person', '@id': `${SITE}/#sarah-evans`, name: 'Sarah Evans', url: SITE };
const crumbsLD = (trail) => ({
  '@context': 'https://schema.org', '@type': 'BreadcrumbList',
  itemListElement: trail.map(([name, p], i) => ({ '@type': 'ListItem', position: i + 1, name, item: SITE + p })),
});
const crumbs = (trail) => `<nav class="crumbs" aria-label="Breadcrumb">${trail.map(([n, p], i) => (i === trail.length - 1 ? esc(n) : `<a href="${p}">${esc(n)}</a> / `)).join('')}</nav>`;

// ---------- homepage ----------
const freeSkills = C.skill.filter((s) => s.free_or_paid === 'free' && s.featured);
{
  const tpl = fs.readFileSync(path.join(ROOT, 'content', 'pages', 'home.html'), 'utf8').replace(/<!--[\s\S]*?-->\s*/, '');
  let n = 0;
  const body = tpl
    .replace('{{FREE_SKILL_CARDS}}', `<div class="grid">${freeSkills.map((s) => card('skill', s, { trackId: 'home->skill:' + s.slug })).join('')}</div>`)
    .replace(/\{\{SEARCH_FORM\}\}/g, () => searchForm(`q-home-${++n}`));
  const banner = `<div class="sa-banner" data-banner="geo101" data-until="2026-10-24T00:00:00-07:00" hidden><div class="sa-wrap"><span><strong>GEO 101 for Agencies</strong> — live training Oct 23, 12–1 pm PT. <a href="/geo-101">Details →</a></span><button type="button" aria-label="Dismiss">×</button></div></div>`;
  write('/', layout({
    title: 'askSarah.ai — I figure things out for a living | Sarah Evans',
    description: "The AI Skills, tools, shortcuts and systems Sarah Evans actually uses, plus the stuff she'd send to a friend. Some free, some paid, all tested.",
    pathname: '/', body, banner,
    jsonld: [{ '@context': 'https://schema.org', '@type': 'WebSite', name: 'askSarah.ai', url: SITE,
      potentialAction: { '@type': 'SearchAction', target: `${SITE}/search?q={query}`, 'query-input': 'required name=query' } }],
  }));
}

// ---------- skills ----------
const DEFAULT_INSTRUCTIONS = {
  Claude: ['Download the .zip. Don’t unzip it.', 'In the Claude app, open Settings and find Skills.', 'Upload the .zip and switch it on.', 'Start a new chat and just ask for the thing. Claude picks up the Skill on its own.'],
  'Claude Code': ['Download and unzip the file.', 'Move the folder into ~/.claude/skills/', 'Open Claude Code and describe what you need, or call it by name. No restart needed.'],
};
function skillCTA(s) {
  if (s.free_or_paid === 'paid' && s.status === 'available') {
    const cents = Math.round(Number(s.price) * 100);
    return `<p class="price">${fmtPrice(s.price)}</p>
<button class="btn btn-primary" data-buy="${esc(s.stripe_id || s.slug)}" data-name="${esc(s.title)}" data-cents="${cents}">Buy ${esc(s.title)} →</button>
<small>One-time purchase. Instant download after checkout. Questions: <a href="mailto:sarah@evans-global.com">sarah@evans-global.com</a></small>`;
  }
  if (s.free_or_paid === 'free' && has(s.download)) {
    return `<p class="price">Free</p>
<a class="btn btn-primary" href="${esc(s.download)}" download data-track="skill_download" data-track-id="${esc(s.slug)}">Download the Skill →</a>
<small>No signup. If you like it, the <a href="${SUBSCRIBE_URL}" target="_blank" rel="noopener" data-track="email_signup_click">emails</a> are where new ones show up first.</small>`;
  }
  return `<p class="price">${s.free_or_paid === 'free' ? 'Free' : s.price ? fmtPrice(s.price) : 'Paid'}</p>
<p style="margin:.25rem 0 0"><strong>Not out yet.</strong> I'm still testing it on my own work.</p>
<a class="btn btn-primary" href="${SUBSCRIBE_URL}" target="_blank" rel="noopener" data-track="email_signup_click" data-track-id="${esc(s.slug)}">Get it the day it ships →</a>
<small>I'll send it when it's ready. That's the whole email.</small>`;
}
for (const s of C.skill) {
  const p = `/skills/${s.slug}`;
  const packs = C.pack.filter((pk) => arr(pk.included).some((i) => i && typeof i === 'object' && i.slug === s.slug) || arr(s.pack_membership).includes(pk.slug));
  const ex = s.example_ref ? find(s.example_ref.type, s.example_ref.slug) : null;
  const platforms = arr(s.platforms).length ? arr(s.platforms) : ['Claude'];
  const instr = has(s.instructions) ? arr(s.instructions) : DEFAULT_INSTRUCTIONS[platforms[0]] || DEFAULT_INSTRUCTIONS.Claude;
  const b = badgeFor('skill', s);
  const blocks = [
    has(s.what_it_does) || has(s.what_it_does_list) ? `<div class="block"><h2>What it does</h2>${paras(s.what_it_does)}${has(s.what_it_does_list) ? `<ul class="pills">${arr(s.what_it_does_list).map((x) => `<li>${esc(x)}</li>`).join('')}</ul>` : ''}${has(s.what_it_does_after) ? `<p style="margin-top:1rem">${esc(s.what_it_does_after)}</p>` : ''}</div>` : '',
    has(s.when_to_use) ? `<div class="block"><h2>When to use it</h2>${list(s.when_to_use)}</div>` : '',
    has(s.what_to_give_it) ? `<div class="block"><h2>What to give it</h2>${list(s.what_to_give_it)}</div>` : '',
    has(s.what_you_get) ? `<div class="block"><h2>What you get back</h2>${list(s.what_you_get)}</div>` : '',
    ex ? `<div class="block"><h2>How I actually use it</h2><p><strong>${esc(ex.title)}.</strong> ${esc(arr(ex.story)[0] || '')}</p>${ex.prompt ? `<div class="prompt"><p>${esc(ex.prompt)}</p></div>` : ''}<p><a class="textlink" href="${urlFor('ai-use', ex)}">Read the whole thing →</a></p></div>`
      : has(s.example) ? `<div class="block"><h2>Example</h2>${paras(s.example)}</div>` : '',
    `<div class="block"><h2>How to use this in ${esc(platforms[0])}</h2><ol>${instr.map((x) => `<li>${esc(x)}</li>`).join('')}</ol>${platforms[0] === 'Claude Code' ? '<p class="muted">Built for Claude Code, which needs a paid Claude plan.</p>' : '<p class="muted">Works on any Claude plan that has Skills turned on.</p>'}</div>`,
    packs.length ? `<div class="block"><h2>Also in</h2>${packs.map((pk) => `<p><a class="textlink" href="${urlFor('pack', pk)}">${esc(pk.title)}</a> <span class="muted">— ${esc(pk.promise)}</span></p>`).join('')}</div>` : '',
  ].filter(Boolean).join('\n');
  const isPaid = s.free_or_paid === 'paid';
  const body = `<section class="hero"><div class="wrap">
${crumbs([['Skills', '/skills'], [s.title, p]])}
<div class="detail-head read">
  <div class="badges"><span class="badge badge-type">Skill</span>${b ? `<span class="badge ${b.cls}">${esc(b.text)}</span>` : ''}${arr(s.category).map((c) => `<span class="badge badge-soon">${esc(c)}</span>`).join('')}</div>
  <h1 style="font-size:clamp(2.2rem,5vw,3.6rem)">${esc(s.title)}</h1>
  <p class="lede">${esc(s.promise)}</p>
</div>
<div class="detail-grid">
  <div>
    ${blocks}
  </div>
  <aside><div class="cta-box">${skillCTA(s)}</div></aside>
</div>
${related(s, 'skill:' + s.slug)}
</div></section>`;
  write(p, layout({
    title: `${s.title}${isPaid ? '' : ' (free)'} — a Claude Skill by Sarah Evans`,
    description: s.description || s.promise,
    pathname: p, body, ogType: 'article', draft: s.published === false,
    view: isPaid ? 'paid_view' : 'skill_view', viewId: s.slug,
    jsonld: [
      crumbsLD([['Skills', '/skills'], [s.title, p]]),
      { '@context': 'https://schema.org', '@type': isPaid ? 'Product' : 'CreativeWork', name: s.title, description: s.description || s.promise,
        url: SITE + p, author: personLD, ...(isPaid ? { brand: { '@type': 'Brand', name: 'askSarah.ai' }, offers: { '@type': 'Offer', price: String(s.price), priceCurrency: 'USD', availability: s.status === 'available' ? 'https://schema.org/InStock' : 'https://schema.org/PreOrder', url: SITE + p } } : { isAccessibleForFree: true }),
        ...(s.updated_at ? { dateModified: s.updated_at } : {}) },
    ],
  }));
}

// skills landing
{
  const free = C.skill.filter((s) => s.free_or_paid === 'free');
  const paid = C.skill.filter((s) => s.free_or_paid === 'paid');
  const popular = C.skill.filter((s) => s.popular);
  const packHTML = C.pack.map((pk) => `<article class="pack" id="${esc(pk.slug)}">
  <div class="badges"><span class="badge badge-type">Skill Pack</span>${pk.status === 'coming-soon' ? '<span class="badge badge-soon">Coming soon</span>' : ''}</div>
  <h3 style="font-size:1.6rem">${esc(pk.title)}</h3>
  ${pk.price ? `<p class="price">${fmtPrice(pk.price)}</p>` : ''}
  <p class="lede" style="font-size:1.05rem">${esc(pk.promise)}</p>
  ${has(pk.description) ? `<p class="muted">${esc(pk.description)}</p>` : ''}
  <p class="eyebrow" style="margin:1rem 0 0">${arr(pk.included).length} Skills</p>
  <ol>${arr(pk.included).map((i) => (typeof i === 'object' ? `<li><a href="/skills/${esc(i.slug)}">${esc(i.name)}</a> <span class="badge badge-free">Free now</span></li>` : `<li>${esc(i)}</li>`)).join('')}</ol>
  ${pk.status === 'coming-soon' ? `<p style="margin-top:1rem"><a class="textlink" href="${SUBSCRIBE_URL}" target="_blank" rel="noopener" data-track="email_signup_click" data-track-id="${esc(pk.slug)}">Tell me when it's out →</a></p>` : ''}
</article>`).join('\n');
  const body = `<section class="hero"><div class="wrap">
  <p class="eyebrow">Skills</p>
  <h1 style="max-width:16ch">Stop rewriting the same prompt.</h1>
  <div class="hero-grid">
    <div class="stack-lines hero-copy">
      <p class="lede">I did it too.</p>
      <p>"Here's how I want this formatted."<br>"Don't make it sound like AI."<br>"Remember the audience."<br>"Do this first."<br>"Never do that."</p>
      <p>And then three chats later, I'd explain the whole thing again.</p>
      <p>That's why I became obsessed with Skills.</p>
      <p>A Skill isn't just a really long prompt.</p>
      <p>It's a set of instructions, rules, context and judgment that AI can use again and again.</p>
      <p>Basically:</p>
      <p class="pull">Prompts tell AI what to do.<br>Skills teach AI how you do it.</p>
      <p>That difference is huge.</p>
      <p>I've started building Skills for all the things I repeatedly ask AI to help me do—running meetings, making decisions, researching, organizing my brain, reviewing work, planning, writing like myself and handling the hundred random things that happen between 6 a.m. and bedtime.</p>
      <p>I'm putting the best ones here.</p>
      <p>You don't need to know how to code.<br>You do not need to become an "AI expert."</p>
      <p>You need to find one annoying thing you keep doing manually and make AI better at helping you do it.</p>
      <p class="big-line">Start there.</p>
    </div>
    <div class="ask-card">
      <p class="eyebrow">On this page</p>
      <div class="quick" style="margin-top:0">
        <a class="chip" href="#free">Free Skills</a>
        <a class="chip" href="#premium">Premium Skills</a>
        <a class="chip" href="#packs">Skill Packs</a>
        ${popular.length ? '<a class="chip" href="#popular">Most Popular</a>' : ''}
        <a class="chip" href="#how">How Skills Work</a>
      </div>
      <p style="margin:1.5rem 0 0" class="muted">Free ones first. Seriously.</p>
      <p style="margin:.5rem 0 0"><a class="btn btn-primary" href="#free">Get a free Skill →</a></p>
    </div>
  </div>
</div></section>

<section class="rule-top" id="free"><div class="wrap">
  <div class="section-head">
    <p class="eyebrow"><span class="badge badge-free">Free</span> Free Skills</p>
    <h2>Use these before you buy anything from me.</h2>
    <p>Seriously.<br>If they don't make your life easier, keep your money.</p>
  </div>
  <div class="grid">${free.map((s) => card('skill', s, { trackId: 'skills->' + s.slug })).join('')}</div>
</div></section>

${popular.length ? `<section class="rule-top" id="popular"><div class="wrap"><div class="section-head"><p class="eyebrow">Most Popular</p><h2>What people actually use.</h2></div><div class="grid">${popular.map((s) => card('skill', s)).join('')}</div></div></section>` : ''}

<section class="rule-top" id="premium"><div class="wrap">
  <div class="section-head">
    <p class="eyebrow"><span class="badge badge-paid">Paid</span> Premium Skills</p>
    <h2>Some took enough work that I'm charging you for them. 🙂</h2>
    <p>Available now. One-time purchase, instant download.</p>
  </div>
  <div class="grid">${paid.map((s) => card('skill', s, { trackId: 'skills->' + s.slug })).join('')}</div>
  <p class="muted" style="margin-top:1.5rem">Looking for the PR and writing Skills? They're still in the <a href="/claude-skills">original Skills store</a>.</p>
</div></section>

<section class="rule-top" id="packs"><div class="wrap">
  <div class="section-head">
    <p class="eyebrow">Skill Packs</p>
    <h2>A whole set, built to work together.</h2>
  </div>
  <div class="grid" style="grid-template-columns:repeat(auto-fill,minmax(min(100%,460px),1fr))">${packHTML}</div>
</div></section>

<section class="band" id="how"><div class="wrap">
  <div class="feature" style="border:0">
    <div><p class="eyebrow">How Skills work</p><h2>A prompt tells AI what you want right now.</h2></div>
    <div class="stack-lines">
      <p class="big-line">A Skill teaches it how you want something done repeatedly.</p>
      <p>A Skill is a small folder with a file of instructions in it. You add it to Claude once. After that, when you ask for the thing the Skill is for, Claude follows your instructions without you pasting them in again.</p>
      <ol>
        <li>Download the Skill.</li>
        <li>Add it to Claude. Every Skill page has the exact steps.</li>
        <li>Ask for the thing. That's it.</li>
      </ol>
      <p class="muted">Each Skill page says whether it's built for the Claude app or Claude Code.</p>
    </div>
  </div>
</div></section>

<section><div class="wrap">${capture()}</div></section>`;
  write('/skills', layout({
    title: 'Claude Skills by Sarah Evans — free and premium',
    description: 'Prompts tell AI what to do. Skills teach AI how you do it. The Claude Skills Sarah Evans builds and uses for work, decisions, meetings, research and everyday life. Start with a free one.',
    pathname: '/skills', body,
    jsonld: [{ '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'Claude Skills', url: SITE + '/skills',
      hasPart: C.skill.map((s) => ({ '@type': 'CreativeWork', name: s.title, url: SITE + '/skills/' + s.slug })) }],
  }));
}

// ---------- AI uses (flagship) ----------
const AI_CATEGORIES = ['Work', 'CEO', 'Meetings', 'Decisions', 'Research', 'Organization', 'Money', 'Shopping', 'Travel', 'Parenting', 'School', 'Food', 'Fitness', 'Beauty', 'Style', 'Home', 'Learning', 'Entertainment', 'Life'];
const aiUses = [...C['ai-use']].sort((a, b) => a.number - b.number);
for (const u of aiUses) {
  const p = `/things-ai-can-do/${u.slug}`;
  const skill = u.related_skill ? find('skill', u.related_skill) : null;
  const stack = u.related_stack ? find('stack', u.related_stack) : null;
  const body = `<section class="hero"><div class="wrap read">
${crumbs([['Things AI can do', '/things-ai-can-do'], [`#${u.number}`, p]])}
<div class="badges"><span class="badge badge-new">#${u.number}</span><span class="badge badge-soon">${esc(u.category)}</span></div>
<h1 style="font-size:clamp(2rem,5vw,3.2rem)">${esc(u.title)}</h1>
<div class="stack-lines" style="font-size:1.1rem">${paras(u.story)}</div>
${u.prompt ? `<div class="prompt"><p id="prompt-${esc(u.slug)}">${esc(u.prompt)}</p><button class="btn btn-ghost copy" data-copy="prompt-${esc(u.slug)}" type="button">Copy</button></div>` : ''}
<div class="stack-lines" style="font-size:1.1rem">${paras(u.after)}</div>
<dl class="facts block" style="margin-top:2rem">
  ${u.tool ? `<dt>What I use</dt><dd>${stack && stack.published !== false ? `<a href="${urlFor('stack', stack)}">${esc(u.tool)}</a>` : esc(u.tool)}</dd>` : ''}
  ${skill ? `<dt>Skill</dt><dd><a href="${urlFor('skill', skill)}">${esc(skill.title)}</a> <span class="badge ${badgeFor('skill', skill).cls}">${esc(badgeFor('skill', skill).text)}</span></dd>` : ''}
  ${has(u.shortcut) ? `<dt>Shortcut</dt><dd>${esc(u.shortcut)}</dd>` : ''}
</dl>
${related(u, 'ai-use:' + u.slug)}
</div></section>
<section><div class="wrap">${capture('New entries go out by email first.', 'Actual uses. Not hypothetical ones.')}</div></section>`;
  write(p, layout({
    title: `${u.title} — Things I didn't know AI could do | askSarah.ai`,
    description: `${arr(u.story)[0] || ''} ${u.prompt || ''}`.trim().slice(0, 158),
    pathname: p, body, ogType: 'article', draft: u.published === false,
    jsonld: [crumbsLD([['Things AI can do', '/things-ai-can-do'], [u.title, p]]),
      { '@context': 'https://schema.org', '@type': 'Article', headline: u.title, author: personLD, url: SITE + p, ...(u.updated_at ? { dateModified: u.updated_at } : {}) }],
  }));
}
{
  const cats = AI_CATEGORIES.filter((c) => aiUses.some((u) => u.category === c));
  const body = `<section class="hero"><div class="wrap">
  <p class="eyebrow">The running list</p>
  <h1 style="max-width:18ch">Things I didn't know AI could do until I tried it.</h1>
  <div class="hero-grid">
    <div class="stack-lines hero-copy">
      <p class="lede">I don't need AI to write me another blog post.</p>
      <p class="big-line">I need it to help me think.</p>
      <p>Make a decision. Prepare for a conversation. Research something I don't have six hours to research. Organize the thought currently ricocheting around my brain. Challenge me when I'm convinced I'm right. Turn chaos into something I can actually act on.</p>
      <p>This is the running list of the ways I'm using AI in real life.</p>
      <p>Not hypothetical use cases.<br>Actual ones.</p>
    </div>
    <div class="ask-card">
      <p class="eyebrow">${aiUses.length} so far</p>
      <p>Each one has what I actually ask, the tool I use, and the Skill if there is one.</p>
      <p class="muted" style="margin:0">New ones get added as I figure them out.</p>
    </div>
  </div>
</div></section>
<section class="rule-top"><div class="wrap">
  ${cats.length > 1 ? `<div class="quick" data-filter-group data-filter-target="#uses .card" style="margin-bottom:1.5rem"><button class="chip" data-filter="all" aria-pressed="true" type="button">All</button>${cats.map((c) => `<button class="chip" data-filter="${esc(c)}" aria-pressed="false" type="button">${esc(c)}</button>`).join('')}</div>` : ''}
  <div class="grid" id="uses">${aiUses.map((u) => `<article class="card" data-cats="${esc(u.category)}">
    <p class="card-num">#${u.number} · ${esc(u.category)}</p>
    <h3><a href="${urlFor('ai-use', u)}">${esc(u.title)}</a></h3>
    <p>${esc(arr(u.story)[0] || '')}</p>
    <div class="card-foot"><span>${esc(u.tool || '')}</span><span class="go" aria-hidden="true">→</span></div>
  </article>`).join('')}</div>
</div></section>
<section><div class="wrap">${capture('New entries go out by email first.', 'Actual uses. Not hypothetical ones.')}</div></section>`;
  write('/things-ai-can-do', layout({
    title: "Things I didn't know AI could do until I tried it — Sarah Evans",
    description: "Sarah Evans' running list of the ways she actually uses AI in real life: decisions, meetings, research, planning and more. What she asks, which tool, and the Skill behind it.",
    pathname: '/things-ai-can-do', body,
    jsonld: [{ '@context': 'https://schema.org', '@type': 'CollectionPage', name: "Things I didn't know AI could do until I tried it", url: SITE + '/things-ai-can-do', author: personLD }],
  }));
}

// ---------- Stack ----------
const STACK_CATEGORIES = ['AI', 'Work', 'Creator', 'Tech', 'Travel', 'Home', 'Fitness', 'Style + Beauty'];
for (const e of C.stack) {
  const p = `/stack/${e.slug}`;
  const out = e.affiliate_url || e.url;
  const qa = [
    ['What I use it for', e.what_i_use_it_for], ["What I don't use it for", e.what_i_dont_use_it_for], ["Why it's still here", e.why_it_stays],
    ['Do I pay for it?', e.do_i_pay], ['Who actually needs it', e.who_needs_it], ['Who probably doesn’t', e.who_doesnt],
    ['Favorite feature', e.favorite_feature], ["If I stopped using it, I'd use", e.alternative],
  ].filter(([, v]) => has(v));
  const body = `<section class="hero"><div class="wrap">
${crumbs([["Sarah's Stack", '/stack'], [e.title, p]])}
<div class="detail-head read">
  <div class="badges"><span class="badge badge-type">Sarah's Stack</span><span class="badge badge-soon">${esc(e.category)}</span></div>
  <h1 style="font-size:clamp(2.2rem,5vw,3.6rem)">${esc(e.title)}</h1>
  ${has(e.short_description) ? `<p class="lede">${esc(e.short_description)}</p>` : ''}
</div>
<div class="detail-grid">
  <div>
    ${e.affiliate_url ? `<p class="disclosure"><strong>Heads up:</strong> ${esc(e.affiliate_disclosure || 'I make money if you buy through my link. It doesn’t change what I think of it.')}</p>` : ''}
    <dl class="qa">${qa.map(([q, a]) => `<dt>${esc(q)}</dt><dd>${esc(a)}</dd>`).join('')}</dl>
  </div>
  <aside><div class="cta-box">
    ${out ? `<a class="btn btn-primary" href="${esc(out)}" target="_blank" rel="${e.affiliate_url ? 'sponsored noopener' : 'noopener'}" data-track="${e.affiliate_url ? 'affiliate_click' : 'stack_outbound'}" data-track-id="${esc(e.slug)}">Go to ${esc(e.title)} →</a>` : ''}
    ${e.affiliate_url ? '<small>Affiliate link. I earn a commission if you buy.</small>' : '<small>Not an affiliate link.</small>'}
    ${e.last_reviewed ? `<small style="margin-top:.75rem">Last reviewed ${esc(fmtDate(e.last_reviewed))}</small>` : ''}
  </div></aside>
</div>
${related(e, 'stack:' + e.slug)}
</div></section>`;
  write(p, layout({ title: `${e.title} — why it's in Sarah's Stack`, description: e.short_description || `What Sarah Evans actually uses ${e.title} for, whether she pays for it, and who should skip it.`,
    pathname: p, body, ogType: 'article', draft: e.published === false, jsonld: [crumbsLD([["Sarah's Stack", '/stack'], [e.title, p]])] }));
}
{
  const stack = C.stack.filter((e) => e.published !== false || DRAFTS);
  const body = `<section class="hero"><div class="wrap">
  <p class="eyebrow">Sarah's Stack</p>
  <h1 style="max-width:16ch">Everything I'm actually using right now.</h1>
  <div class="hero-grid">
    <div class="stack-lines hero-copy">
      <p class="lede">There is an absurd amount of software, technology and stuff in my life.</p>
      <p>Most of it does not survive.<br>This is what did.</p>
      <p>For every one, I'll tell you:</p>
      <ul><li>what I actually use it for</li><li>what I don't use it for</li><li>whether I pay for it</li><li>whether I think you should</li><li>what I would use instead if I stopped using it</li></ul>
      <p class="big-line">If it's here, I've actually used it.</p>
    </div>
    <div class="ask-card">
      <p class="eyebrow">Categories</p>
      <div class="quick" style="margin-top:0" ${stack.length ? 'data-filter-group data-filter-target="#stack .card"' : ''}>
        ${stack.length ? '<button class="chip" data-filter="all" aria-pressed="true" type="button">All</button>' : ''}
        ${STACK_CATEGORIES.map((c) => (stack.some((e) => e.category === c) ? `<button class="chip" data-filter="${esc(c)}" aria-pressed="false" type="button">${esc(c)}</button>` : `<span class="chip" aria-disabled="true">${esc(c)}</span>`)).join('')}
      </div>
      <p class="muted" style="margin:1.25rem 0 0">If I make money when you buy something, the entry says so.</p>
    </div>
  </div>
</div></section>
<section class="rule-top"><div class="wrap">
  ${stack.length ? `<div class="grid" id="stack">${stack.map((e) => card('stack', e, { trackId: 'stack->' + e.slug })).join('')}</div>`
    : `<div class="empty"><strong>The first entries are going up soon.</strong><br>I'm writing each one properly: what I use it for, what I don't, whether I pay. I'm not listing anything I haven't actually used.</div>`}
</div></section>
<section><div class="wrap">${capture()}</div></section>`;
  write('/stack', layout({ title: "Sarah's Stack — the tools and stuff Sarah Evans actually uses", description: 'The AI tools, work tools, tech, travel gear and more that survived in Sarah Evans’ life. What she uses each for, whether she pays, and who should skip it.', pathname: '/stack', body }));
}

// ---------- Phase 3 landings: Shortcuts / Systems / Edit ----------
function comingLanding({ pathname, eyebrow, h1, lines, upcomingLabel, upcoming, chips, title, description, captureHead, itemsType }) {
  const items = C[itemsType] || [];
  const body = `<section class="hero"><div class="wrap">
  <p class="eyebrow">${esc(eyebrow)}</p>
  <h1 style="max-width:18ch">${esc(h1)}</h1>
  <div class="hero-grid">
    <div class="stack-lines hero-copy">${lines}</div>
    <div class="ask-card">
      ${chips ? `<p class="eyebrow">Categories</p><div class="quick" style="margin-top:0">${chips.map((c) => `<span class="chip" aria-disabled="true">${esc(c)}</span>`).join('')}</div>` : ''}
      <p class="muted" style="margin:1.25rem 0 .75rem">Want something now? The free Skills are ready.</p>
      <a class="textlink" href="/skills#free">Start with something free →</a>
    </div>
  </div>
</div></section>
<section class="rule-top"><div class="wrap">
  ${items.length ? `<div class="grid">${items.map((x) => card(itemsType, x)).join('')}</div>` : `<p class="eyebrow">${esc(upcomingLabel)}</p>${upcoming.length ? `<ul class="upcoming">${upcoming.map((u) => `<li><span>${esc(u)}</span><span>In the works</span></li>`).join('')}</ul>` : ''}`}
</div></section>
<section><div class="wrap">${capture(captureHead)}</div></section>`;
  write(pathname, layout({ title, description, pathname, body }));
}
comingLanding({
  pathname: '/shortcuts', itemsType: 'shortcut', eyebrow: 'Shortcuts', h1: 'Little problems. Useful answers.',
  lines: `<p class="lede">These exist because I don't want to read a 2,000-word article when I have a problem.</p><p>I want someone to tell me what to do.</p><p>So these are the shortcuts. One problem, my answer, what to do and what I use.</p>`,
  upcomingLabel: 'First up', chips: ['AI', 'Work', 'CEO', 'Decisions', 'Organization', 'Career', 'Travel', 'Shopping', 'Life'],
  upcoming: ['How I prep for a difficult conversation', 'How I turn a brain dump into an actual plan', 'How I use AI before an important meeting', 'How I research a purchase without losing three hours', "How I decide when I've researched something to death", 'How I pack for a short trip', 'How I turn meeting notes into actual decisions', 'How I figure out what only I should be doing'],
  title: 'Shortcuts — quick answers to specific problems | askSarah.ai', description: 'Not long articles. One specific problem, Sarah Evans’ answer, and what to do about it.',
  captureHead: 'Want the shortcuts as they land?',
});
comingLanding({
  pathname: '/systems', itemsType: 'system', eyebrow: 'Systems', h1: 'Some things need more than a shortcut.',
  lines: `<p class="lede">These are the systems I've built because I needed them myself.</p><p>How I manage my week.<br>How I decide what only I should be doing.<br>How I use AI without creating more work for myself.<br>How I stop ideas from living in 14 tabs, three Notes files, a Slack message to myself and the notebook I can't find.</p><p>They aren't productivity theater.<br>They're meant to actually be used.</p>`,
  upcomingLabel: 'On the workbench', chips: ['CEO', 'Personal AI', 'Organization', 'Career', 'Personal Brand'],
  upcoming: ['CEO Operating System', 'Personal AI System', 'Personal Organization System', 'Career System', 'Personal Brand System'],
  title: 'Systems — the operating systems Sarah Evans actually runs on | askSarah.ai', description: 'Practical systems for running your week, your work and your AI. Guides, templates, Skills and checklists Sarah Evans built for herself.',
  captureHead: 'Get the first System when it ships.',
});
comingLanding({
  pathname: '/edit', itemsType: 'edit', eyebrow: "Sarah's Edit", h1: 'I am the person my friends text: "Which one?"',
  lines: `<p>"Is this worth it?"<br>"What should I wear?"<br>"What do I buy her?"<br>"Where should we stay?"<br>"Do I need this?"</p><p class="lede">This is where I'm putting the answers.</p><p>Things I love. Things I returned. Things worth spending more on. Things absolutely not worth spending more on.</p><p>And the occasional thing I will defend with an unreasonable amount of enthusiasm.</p>`,
  upcomingLabel: 'Coming soon', chips: ["What I'm Buying", 'Beauty', 'Style', 'Gifts', 'Travel', 'Tech', 'Favorites'], upcoming: [],
  title: "Sarah's Edit — what's worth buying and what isn't | askSarah.ai", description: 'Things Sarah Evans loves, things she returned, and what is and isn’t worth spending more on. Every affiliate link disclosed.',
  captureHead: 'First picks go out by email.',
});

// ---------- Search ----------
const index = [];
const push = (type, it, extra = {}) => {
  const b = badgeFor(type, it);
  index.push({ type, typeLabel: TYPES[type].label, title: titleOf(it), url: urlFor(type, it), description: summaryOf(type, it),
    category: arr(it.category).join(' '), badge: b ? b.text : '', badgeClass: b ? b.cls : '', ...extra });
};
C.skill.forEach((s) => push('skill', s, { keywords: [...arr(s.what_it_does_list), ...arr(s.when_to_use), ...arr(s.what_you_get)].join(' ') }));
C.pack.forEach((p) => push('pack', p, { keywords: arr(p.included).map((i) => (typeof i === 'object' ? i.name : i)).join(' ') }));
aiUses.forEach((u) => push('ai-use', u, { description: arr(u.story)[0] || '', keywords: [u.prompt, ...arr(u.after), u.tool].join(' ') }));
C.stack.forEach((e) => push('stack', e));
['shortcut', 'system', 'edit'].forEach((t) => C[t].forEach((x) => push(t, x)));
for (const a of articles) {
  let desc = a.description;
  const f = path.join(ROOT, a.slug + '.html');
  if (!desc && fs.existsSync(f)) desc = (fs.readFileSync(f, 'utf8').match(/<meta name="description" content="([^"]*)"/) || [])[1] || '';
  push('article', { ...a, description: desc });
}
fs.writeFileSync(path.join(ROOT, 'search-index.json'), JSON.stringify(index));
{
  const types = [['all', 'Everything'], ['skill', 'Skills'], ['ai-use', 'How I use AI'], ['stack', 'Stack'], ['shortcut', 'Shortcuts'], ['system', 'Systems'], ['edit', "Sarah's Edit"], ['article', 'Articles']]
    .filter(([t]) => t === 'all' || index.some((i) => i.type === t) || (t === 'skill' && index.some((i) => i.type === 'pack')));
  const body = `<section class="hero" id="search-app"><div class="wrap read">
  <h1 style="font-size:clamp(2rem,5vw,3.2rem)">What are you trying to figure out?</h1>
  <form class="search-form" id="search-form" action="/search" method="get" role="search">
    <label class="sr-only" for="q">Search</label>
    <input id="q" name="q" type="search" placeholder="Try &quot;meeting&quot;, &quot;decide&quot;, &quot;research&quot;" autocomplete="off" autofocus>
    <button class="btn btn-primary" type="submit">Ask</button>
  </form>
  <div class="quick" id="type-filter" aria-label="Filter by type">${types.map(([t, l], i) => `<button class="chip" type="button" data-type="${t}" aria-pressed="${i === 0}">${esc(l)}</button>`).join('')}</div>
  <p id="search-status" class="muted" role="status" aria-live="polite" style="margin-top:1.5rem">Loading…</p>
  <ul class="results" id="results"></ul>
  <noscript><p>Search needs JavaScript. You can browse <a href="/skills">Skills</a>, <a href="/things-ai-can-do">how I use AI</a> or <a href="/stack">my stack</a> instead.</p></noscript>
</div></section>`;
  write('/search', layout({ title: 'Search askSarah.ai', description: 'Search Skills, shortcuts, systems, Sarah’s Stack and more.', pathname: '/search', body }));
}

// ---------- hand-built pages: shared header/footer ----------
// Every older .html page gets the same header and footer as the new pages,
// between <!--sa:...--> markers. First run swaps out the old nav/footer;
// later runs just refresh what's between the markers.
const LEGACY_SKIP = new Set(['email-template.html', 'card.html', 'google8dc333a5d1a3e4f3.html', 'index-v2-backup.html', 'assessment.html']);
const block = (name, html) => `<!--sa:${name}-->\n${html}\n<!--/sa:${name}-->`;
const legacyHead = '<link rel="stylesheet" href="/assets/chrome.css">\n<link rel="stylesheet" href="/assets/legacy.css">\n<script defer src="/_vercel/insights/script.js"></script>';
let synced = 0;
for (const f of fs.readdirSync(ROOT).filter((f) => f.endsWith('.html') && !LEGACY_SKIP.has(f))) {
  const full = path.join(ROOT, f);
  let html = fs.readFileSync(full, 'utf8');
  if (html.includes(GENERATED)) continue;
  const slug = '/' + f.replace(/\.html$/, '');
  const hdr = block('header', header(slug, { legacy: true }) + '\n<span id="main"></span>');
  const ftr = block('footer', footer());
  const before = html;
  if (html.includes('<!--sa:header-->')) {
    html = html.replace(/<!--sa:header-->[\s\S]*?<!--\/sa:header-->/, hdr)
      .replace(/<!--sa:footer-->[\s\S]*?<!--\/sa:footer-->/, ftr)
      .replace(/<!--sa:head-->[\s\S]*?<!--\/sa:head-->/, block('head', legacyHead));
  } else {
    const bodyAt = html.search(/<body[^>]*>/);
    const navMatch = /<nav\b[^>]*>[\s\S]*?<\/nav>/.exec(html.slice(bodyAt));
    const footMatch = /<footer\b[^>]*>[\s\S]*?<\/footer>/.exec(html);
    if (bodyAt < 0 || !navMatch || !footMatch) { console.warn('  skipped (no nav/footer found):', f); continue; }
    let navStart = bodyAt + navMatch.index, navEnd = navStart + navMatch[0].length;
    // If the nav sits inside a <header>, replace the whole header.
    const hOpen = html.lastIndexOf('<header', navStart), hClose = html.indexOf('</header>', navEnd);
    if (hOpen > bodyAt && hClose > -1 && !html.slice(hOpen, navStart).includes('</header>')) { navStart = hOpen; navEnd = hClose + '</header>'.length; }
    html = html.slice(0, navStart) + hdr + html.slice(navEnd);
    html = html.replace(/<footer\b[^>]*>[\s\S]*?<\/footer>/, ftr)
      .replace(/[ \t]*<div class="mobile-menu"[^>]*>[\s\S]*?<\/div>\n?/, '')
      .replace(/[ \t]*<div class="bg-(?:mesh|orb)[^"]*"><\/div>\n?/g, '')
      .replace('</head>', block('head', legacyHead) + '\n</head>')
      .replace('</body>', block('js', '<script src="/assets/site.js" defer></script>') + '\n</body>')
      .replace(/<html lang="en"(?![^>]*data-theme)/, '<html lang="en" data-theme="light"');
  }
  if (html !== before) { fs.writeFileSync(full, html); synced++; }
}
if (synced) console.log(`Updated header/footer on ${synced} hand-built pages`);

// ---------- remove stale generated pages (renamed, unpublished, deleted) ----------
for (const dir of ['skills', 'stack', 'things-ai-can-do', 'shortcuts', 'systems', 'edit']) {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) continue;
  for (const f of fs.readdirSync(full)) {
    const pathname = `/${dir}/${f.replace(/\.html$/, '')}`;
    const file = path.join(full, f);
    if (f.endsWith('.html') && !written.includes(pathname) && fs.readFileSync(file, 'utf8').includes(GENERATED)) {
      fs.unlinkSync(file);
      console.log('Removed stale page', pathname);
    }
  }
}

// ---------- sitemap ----------
{
  const sm = path.join(ROOT, 'sitemap.xml');
  const src = fs.readFileSync(sm, 'utf8');
  const existing = [...src.matchAll(/<url>[\s\S]*?<\/url>/g)].map((m) => m[0]);
  const locOf = (u) => (u.match(/<loc>([^<]*)<\/loc>/) || [])[1];
  const ours = written.filter((p) => p !== '/search').map((p) => SITE + (p === '/' ? '/' : p));
  const oursSet = new Set(ours);
  const kept = existing.filter((u) => !oursSet.has(locOf(u)));
  const today = new Date().toISOString().slice(0, 10);
  const draftPaths = new Set(Object.values(C).flat().filter((x) => x.published === false).map((x) => x.slug));
  const fresh = ours.filter((u) => !draftPaths.has(u.split('/').pop())).map((u) => `  <url>\n    <loc>${u}</loc>\n    <lastmod>${today}</lastmod>\n  </url>`);
  const head = src.slice(0, src.indexOf('<url>')).trimEnd();
  fs.writeFileSync(sm, `${head}\n${fresh.join('\n')}\n  ${kept.join('\n  ')}\n</urlset>\n`);
}

console.log(`Built ${written.length} pages${DRAFTS ? ' (with drafts: do not commit this build)' : ''}:\n  ${written.join('\n  ')}`);
